import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata, Viewport } from "next";

import "@/styles/core.css";
import { Theme } from "@/theme";

export const metadata: Metadata = {
  title: "Blurple Canvas",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#23272a",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <QueryClientProvider client={queryClient}>
            <ThemeProvider theme={Theme}>{children}</ThemeProvider>
          </QueryClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
