import type { Metadata } from "next";
// import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Blurple Canvas",
  description: "Generated by create next app",
};

export default function Page() {
  return <div>This is the homepage</div>;
}
