import { CanvasView } from "@/components/canvas";
import config from "@/config";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blurple Canvas",
  description: "Generated by create next app",
};

export default async function Page() {
  return (
    <div>
      <CanvasView imageUrl={`${config.apiUrl}/api/v1/canvas/current`} />
    </div>
  );
}
