FROM node:20-alpine

RUN npm install -g pnpm@9.1.0

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm -F frontend build

RUN pnpm store prune

EXPOSE 3000

WORKDIR /app/packages/frontend

CMD ["pnpm", "start"]
