#!/usr/bin/env sh

# Select graphic rendition (SGR) parameters

if [ "$NO_COLOR" != '' ]; then
  # See https://no-color.org
  export RESET=''
  export BOLD=''
  export DIM=''
  export ITALIC=''
  export UNDERLINE=''
  export BLACK=''
  export RED=''
  export GREEN=''
  export YELLOW=''
  export BLUE=''
  export MAGENTA=''
  export CYAN=''
  export WHITE=''
  export ON_BLACK=''
  export ON_RED=''
  export ON_GREEN=''
  export ON_YELLOW=''
  export ON_BLUE=''
  export ON_MAGENTA=''
  export ON_CYAN=''
  export ON_WHITE=''
  export PURE_WHITE=''
else
  export RESET='\033[m'
  export BOLD='\033[1m'
  export DIM='\033[2m'
  export ITALIC='\033[3m'
  export UNDERLINE='\033[4m'
  export BLACK='\033[30m'
  export RED='\033[31m'
  export GREEN='\033[32m'
  export YELLOW='\033[33m'
  export BLUE='\033[34m'
  export MAGENTA='\033[35m'
  export CYAN='\033[36m'
  export WHITE='\033[37m'
  export PURE_WHITE='\033[38;5;231m'
  export ON_BLACK='\033[40m'
  export ON_RED='\033[41m'
  export ON_GREEN='\033[42m'
  export ON_YELLOW='\033[43m'
  export ON_BLUE='\033[44m'
  export ON_MAGENTA='\033[45m'
  export ON_CYAN='\033[46m'
  export ON_WHITE='\033[47m'
fi
