#!/usr/bin/env sh

# ANSI control sequences

export CURSOR_UP='\033[A'
export CURSOR_DOWN='\033[B'
export CURSOR_FORWARD='\033[C'
export CURSOR_BACK='\033[D'
export CURSOR_NEXT_LINE='\033[E'
export CURSOR_PREV_LINE='\033[F'
export CURSOR_START_OF_LINE='\033[G'
export CLEAR_LINE="\033[2K${CURSOR_START_OF_LINE}"

# Select graphic rendition (SGR) parameters

if [ "$NO_COLOR" != '' ]; then
    # See https://no-color.org
    export RESET=''
    export BOLD=''
    export DIM=''
    export ITALIC=''
    export UNDERLINE=''
    export BLACK=''
    export RED=''
    export GREEN=''
    export YELLOW=''
    export BLUE=''
    export MAGENTA=''
    export CYAN=''
    export WHITE=''
    export ON_BLACK=''
    export ON_RED=''
    export ON_GREEN=''
    export ON_YELLOW=''
    export ON_BLUE=''
    export ON_MAGENTA=''
    export ON_CYAN=''
    export ON_WHITE=''
    export BRIGHT_BLACK=''
    export BRIGHT_RED=''
    export BRIGHT_GREEN=''
    export BRIGHT_YELLOW=''
    export BRIGHT_BLUE=''
    export BRIGHT_MAGENTA=''
    export BRIGHT_CYAN=''
    export BRIGHT_WHITE=''
    export ON_BRIGHT_BLACK=''
    export ON_BRIGHT_RED=''
    export ON_BRIGHT_GREEN=''
    export ON_BRIGHT_YELLOW=''
    export ON_BRIGHT_BLUE=''
    export ON_BRIGHT_MAGENTA=''
    export ON_BRIGHT_CYAN=''
    export ON_BRIGHT_WHITE=''
else
    export RESET='\033[m'
    export BOLD='\033[1m'
    export DIM='\033[2m'
    export ITALIC='\033[3m'
    export UNDERLINE='\033[4m'
    export BLACK='\033[30m'
    export RED='\033[31m'
    export GREEN='\033[32m'
    export YELLOW='\033[33m'
    export BLUE='\033[34m'
    export MAGENTA='\033[35m'
    export CYAN='\033[36m'
    export WHITE='\033[37m'
    export ON_BLACK='\033[40m'
    export ON_RED='\033[41m'
    export ON_GREEN='\033[42m'
    export ON_YELLOW='\033[43m'
    export ON_BLUE='\033[44m'
    export ON_MAGENTA='\033[45m'
    export ON_CYAN='\033[46m'
    export ON_WHITE='\033[47m'
    export BRIGHT_BLACK='\033[90m'
    export BRIGHT_RED='\033[91m'
    export BRIGHT_GREEN='\033[92m'
    export BRIGHT_YELLOW='\033[93m'
    export BRIGHT_BLUE='\033[94m'
    export BRIGHT_MAGENTA='\033[95m'
    export BRIGHT_CYAN='\033[96m'
    export BRIGHT_WHITE='\033[97m'
    export ON_BRIGHT_BLACK='\033[100m'
    export ON_BRIGHT_RED='\033[101m'
    export ON_BRIGHT_GREEN='\033[102m'
    export ON_BRIGHT_YELLOW='\033[103m'
    export ON_BRIGHT_BLUE='\033[104m'
    export ON_BRIGHT_MAGENTA='\033[105m'
    export ON_BRIGHT_CYAN='\033[106m'
    export ON_BRIGHT_WHITE='\033[107m'
fi
