#!/usr/bin/env sh

. scripts/ansiControlSequences.sh

# Prevent commits to main branch
if [ $(git branch --show-current) = main ]; then
  printf '%b%bCommit aborted.%b Commits to the main branch aren’t allowed. Please switch to a feature branch:\n' "$BOLD" "$RED" "$RESET"
  printf '\n'
  printf '  %bgit switch -c new-branch-name%b\n' "$BOLD" "$RESET"
  printf '\n'
  exit 1
fi

pnpm check:fix
